server:
  port: 9999

spring:
  # 数据源
  datasource:
    url: jdbc:mysql://localhost:3306/vape?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: select 1
  jpa:
    show-sql: true
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

mybatis:
  mapper-locations: classpath:mapper/*.xml

auth:
  expireTime: 3600000
  secret: 123abc
